In [18]:
import requests
from bs4 import BeautifulSoup,SoupStrainer
import pandas as pd
from IPython.display import Markdown, display,HTML,Image
from selenium import webdriver
import time
from pandas.plotting import table 
import matplotlib.pyplot as plt
import string

import warnings
warnings.filterwarnings("ignore")

# Borrowed the offset idea from this (much more professionally done) tableau page
# https://public.tableau.com/app/profile/heidi.stockton/viz/PuzzlesofJaneStreet/JaneStreet
# No adjustments for similar names etc (apologies)

In [20]:
# get the solution links
pages = ['https://www.janestreet.com/puzzles/archive/index.html']+['https://www.janestreet.com/puzzles/archive/page'+str(i)+'/index.html' for i in range(2,13)]
links =  ['https://www.janestreet.com/puzzles/current-puzzle/']
for url in pages:
    res = requests.get(url,verify=False)
    soup = BeautifulSoup(res.content, 'html.parser')
    links += ['https://www.janestreet.com/'+i['href'] for i in soup.find_all('a', {'class' :'solution-link'})]

In [11]:
# scrape the names of solvers
participants = []
order = 1
driver = webdriver.Firefox()
for url in links:
    driver.get(url)
    time.sleep(5)
    htmlSource = driver.page_source
    soup = BeautifulSoup(htmlSource, 'html.parser')
    participants += [[str(url).split("/")[-1],i.split(" (")[0],order] for i in soup.find_all('p', {'class' :'correct-submissions'})[0].stripped_strings]
    order +=1

In [12]:
outputs = []
for newcomer_offset in [10]:
    df = pd.DataFrame(participants,columns = ['puzzle','Name','Order'])
    df['Name']=df['Name'].str.lstrip("1234567890. ")
    df['Name'] = df['Name'].str.title()
    df2 = df[['Name','Order']].groupby('Name').agg({'Name':['count'],'Order': ['max']})
    df2.columns = [' '.join(col).strip() for col in df2.columns.values]
    df2.columns = ['Solved','Attempts']
    df2['Score']=df2['Solved']/(df2['Attempts']+ newcomer_offset)
   
df2.sort_values(['Score','Solved'],ascending=False)[:15]

                            Solved  Attempts     Score
Name
Evan Semet                      46        46  0.821429
Karl Mahlburg                   62        70  0.775000
Senthil Rajasekaran             69        81  0.758242
Gareth Owen                     52        61  0.732394
Aaditya Raghavan                54        64  0.729730
Lazar Ilic                      49        58  0.720588
Danica Xiong                    27        28  0.710526
Calvin Pozderac                 72        94  0.692308
Blaine Hill                     23        26  0.638889
Manuel Felizardo Roxo           19        20  0.633333
Josh Richman                    27        33  0.627907
Miguel Barbosa Pereira          32        41  0.627451
Pedro Pereira                   18        20  0.600000
Brandon Cage                    20        24  0.588235
Moritz Kunze & Hai-Yen Van      21        26  0.583333

In [14]:
df2.sort_values('Solved',ascending=False)[:15]

                        Solved  Attempts     Score
Name
Calvin Pozderac             72        94  0.692308
Senthil Rajasekaran         69        81  0.758242
Karl Mahlburg               62        70  0.775000
Sean Egan                   55        88  0.561224
Aaditya Raghavan            54        64  0.729730
Gareth Owen                 52        61  0.732394
Keith Schneider             51        85  0.536842
Lazar Ilic                  49        58  0.720588
Evan Semet                  46        46  0.821429
Heidi Stockton              40       107  0.341880
Sanandan Swaminathan        38        57  0.567164
Sébastien Geeraert          38        79  0.426966
Miguel Barbosa Pereira      32        41  0.627451
Cubist                      31        63  0.424658
Michael Delyser             31        83  0.333333

In [ ]:
import xlwings as xw
sht = xw.Book().sheets[0]
sht.range('a1').options(index=False).value =  df

In [ ]:
#links