In [1]:
import requests
from bs4 import BeautifulSoup,SoupStrainer
import pandas as pd
from IPython.display import Markdown, display,HTML,Image
from selenium import webdriver
import time
from pandas.plotting import table 
import matplotlib.pyplot as plt
import string

# Borrowed the offset idea from this (much more professionally done) tableau page
# https://public.tableau.com/app/profile/heidi.stockton/viz/PuzzlesofJaneStreet/JaneStreet
# No adjustments for similar names etc (apologies)

In [2]:
# get the solution links
pages = ['https://www.janestreet.com/puzzles/archive/index.html']+['https://www.janestreet.com/puzzles/archive/page'+str(i)+'/index.html' for i in range(2,13)]
links =  ['https://www.janestreet.com/puzzles/current-puzzle/']
for url in pages:
    res = requests.get(url)
    soup = BeautifulSoup(res.content, 'html.parser')
    links += ['https://www.janestreet.com/'+i['href'] for i in soup.find_all('a', {'class' :'solution-link'})]

In [3]:
# scrape the names of solvers
participants = []
order = 1
driver = webdriver.Firefox()
for url in links:
    driver.get(url)
    time.sleep(5)
    htmlSource = driver.page_source
    soup = BeautifulSoup(htmlSource, 'html.parser')
    participants += [[str(url).split("/")[-1],i.split(" (")[0],order] for i in soup.find_all('p', {'class' :'correct-submissions'})[0].stripped_strings]
    order +=1

In [16]:
outputs = []
for newcomer_offset in [10]:
    df = pd.DataFrame(participants,columns = ['puzzle','Name','Order'])
    df['Name']=df['Name'].str.lstrip("1234567890. ")
    df['Name'] = df['Name'].str.title()
    df2 = df[['Name','Order']].groupby('Name').agg({'Name':['count'],'Order': ['max']})
    df2.columns = [' '.join(col).strip() for col in df2.columns.values]
    df2.columns = ['Solved','Attempts']
    df2['Score']=df2['Solved']/(df2['Attempts']+ newcomer_offset)
   
df2.sort_values(['Score','Solved'],ascending=False)[:15]

                            Solved  Attempts     Score
Name
Evan Semet                      45        45  0.818182
Karl Mahlburg                   62        69  0.784810
Senthil Rajasekaran             69        80  0.766667
Gareth Owen                     51        60  0.728571
Aaditya Raghavan                53        63  0.726027
Lazar Ilic                      48        57  0.716418
Danica Xiong                    26        27  0.702703
Calvin Pozderac                 72        93  0.699029
Blaine Hill                     23        25  0.657143
Manuel Felizardo Roxo           19        19  0.655172
Miguel Barbosa Pereira          32        40  0.640000
Josh Richman                    26        32  0.619048
Brandon Cage                    20        23  0.606061
Moritz Kunze & Hai-Yen Van      21        25  0.600000
Pedro Pereira                   17        19  0.586207

In [18]:
df2.sort_values('Solved',ascending=False)[:15]

                        Solved  Attempts     Score
Name
Calvin Pozderac             72        93  0.699029
Senthil Rajasekaran         69        80  0.766667
Karl Mahlburg               62        69  0.784810
Sean Egan                   55        87  0.567010
Aaditya Raghavan            53        63  0.726027
Keith Schneider             51        84  0.542553
Gareth Owen                 51        60  0.728571
Lazar Ilic                  48        57  0.716418
Evan Semet                  45        45  0.818182
Heidi Stockton              40       106  0.344828
Sébastien Geeraert          38        78  0.431818
Sanandan Swaminathan        37        56  0.560606
Miguel Barbosa Pereira      32        40  0.640000
Michael Delyser             31        82  0.336957
Cubist                      31        62  0.430556

In [6]:
import xlwings as xw
sht = xw.Book().sheets[0]
sht.range('a1').options(index=False).value =  df

In [7]:
#links